### PR TITLE
Remove convert setting `DeclarePathParametersOnPathItem`

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/928

This PR:
- Removes the OpenAPI convert setting `DeclarePathParametersOnPathItem`. This setting removes path parameters from the parameter object

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
From the description in #928 it seems that the parameter is missing all together instead of being present at the path item level. I don't think we should disable this option but rather fix the behavior in the conversion library

**Comment by irvinesunday** [comment]
> From the description in #928 it seems that the parameter is missing all together instead of being present at the path item level. I don't think we should disable this option but rather fix the behavior in the conversion library

This is currently blocking PowerShell generation. 
Also, I don't think we need this behaviour in DevX API.

**Comment by irvinesunday** [comment]
> From the description in #928 it seems that the parameter is missing all together instead of being present at the path item level. I don't think we should disable this option but rather fix the behavior in the conversion library

This is currently blocking PowerShell generation. 
Also, I don't think we need this behaviour in DevX API.

**Comment by baywet** [comment]
this feature has been introduced to significantly reduce the size of the OpenAPI description, which has been a challenge for generators, converters, etc...
the right thing to do here is to fix the feature, not toss the can down the road as it'll not only benefit kiota but also hidi, other generators, devx API AND PowerShell.

**Comment by irvinesunday** [comment]
This behaviour actually works on the conversion lib. Need to figure out why DevX API is ejecting the parameters from the path item:

image

The parameters are at the bottom of the path item, after the operations.

**Review by baywet — CHANGES_REQUESTED** [review]

**Review by danielmbaluka — APPROVED** [review]

**Comment by irvinesunday** [comment]
DevX API is not translating the path item parameters because currently the slicing only walks the `OpenAPIOperations` object of the `OpenAPIPathItem`. This should be updated in Hidi, in which DevX API will take a dependency on. Issue is being tracked here: https://github.com/microsoft/OpenAPI.NET/issues/834

**Comment by adhiambovivian** [comment]
@irvinesunday  Let's move with this PR so that we can unblock PowerShell to use 1.0.10 preview

**Pull request merged**
