### PR TITLE
Allows synchronous IO

### PR DESCRIPTION
**Pull request by irvinesunday**
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/468

The exception call stack is as below: 

Line 1: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/c7a21c9b2211cf506c6bebfcc7a20b85501d974b/OpenAPIService/OpenApiService.cs#L378
Line 2: https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/c7a21c9b2211cf506c6bebfcc7a20b85501d974b/GraphWebApi/Controllers/OpenApiController.cs#L113

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Is there any specific reason why we don't use async methods instead of blocking the main thread?

**Comment by irvinesunday** [comment]
> Is there any specific reason why we don't use async methods instead of blocking the main thread?

For the specific issue that this PR is fixing, we don't have an alternate `async` option for this [method ](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/c7a21c9b2211cf506c6bebfcc7a20b85501d974b/OpenAPIService/OpenApiService.cs#L378)from the package (`Microsoft.Odata.Edm`)

**Comment by baywet** [comment]
what about doing the following?

```CSharp
using var reader = new StreamReader(csdl);
var cdslTxt = await reader.ReadToEndAsync();
var edmModel = CsdlReader.Parse(XElement.Parse(csdlTxt).CreateReader());
```

**Review by baywet — APPROVED** [review]
thanks for taking the time to implement the changes!

**Pull request merged**
