### PR TITLE
- update snippet generation for java v3

### PR DESCRIPTION
**Pull request by baywet**
depends on https://github.com/microsoftgraph/msgraph-sdk-java/milestone/4

https://github.com/microsoftgraph/microsoft-graph-docs/compare/snippet-generation/31436?expand=1

TODO:
- [x] create a support branch before merging: support/java-2.X

### CODE REVIEW

**Comment by baywet** [comment]
The changes of this generation have been run against raptor here.
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=31836&view=results

It's complaining about the todo stuff as I haven't updated the feature/v3 branch from latest metadata in a while.

**Comment by baywet** [comment]
disregard, this is not ready yet, I was looking at the wrong PR, sorry about that

**Review by zengin — DISMISSED** [review]

**Comment by zengin** [comment]
oops, this was draft :D

**Comment by baywet** [comment]
you're on a roll :D

**Review by zengin — APPROVED** [review]

**Pull request merged**
